fix(qemu): wait for network at stage 1
Qemu network may take some time to start.
Add instructions to wait for network connectivity before to start
install process.

diff --git a/autoroot/install-scripts/qemu/stage-1 b/autoroot/install-scripts/qemu/stage-1
--- a/autoroot/install-scripts/qemu/stage-1
+++ b/autoroot/install-scripts/qemu/stage-1
@@ -12,6 +12,14 @@ source 'install-scripts/qemu/basesys'
 disk='/dev/vda'
 msg "No system password for virtual machines"
 
+msg "Configure network"
+systemctl start dhcpcd.service
+
+msg "Check network availability"
+if ! wait_network 10 ; then
+    error "Cannot setup network connection"
+fi
+
 msg "Prepare partitions"
 prepare_partitions "$disk" swap root
 
